export const PikaNetworkGamemodes = [
  'bedwars',
  'dungeons',
  'genpvp',
  'kitpvp',
  'oneblock',
  'opfactions',
  'oplifesteal',
  'opprison',
  'opskyblock',
  'pillars',
  'skymines',
  'skypvp',
  'survival',
  'unrankedpractice',
] as const;

export type PikaNetworkGamemode = (typeof PikaNetworkGamemodes)[number];

/**
 * valid `mode` values per gamemode
 */
export const PikaNetworkModes = {
  bedwars: ['ALL_MODES', 'DOUBLES', 'QUAD', 'SOLO', 'TRIPLES'],
  dungeons: ['ALL_MODES'],
  genpvp: ['ALL_MODES'],
  kitpvp: ['ALL_MODES'],
  oneblock: ['ALL_MODES'],
  opfactions: ['ALL_MODES'],
  oplifesteal: ['ALL_MODES'],
  opprison: ['ALL_MODES'],
  opskyblock: ['ALL_MODES'],
  pillars: ['Seasonal'],
  skymines: ['ALL_MODES'],
  skypvp: ['ALL_MODES'],
  survival: ['ALL_MODES'],
  unrankedpractice: [
    'ALL_MODES',
    'ARCHER',
    'AXE_PVP',
    'AXE_SHIELD',
    'BATTLE_RUSH',
    'BED_FIGHT',
    'BOXING',
    'BUILD_UHC',
    'COMBO',
    'CRYSTAL',
    'DEBUFF',
    'DIAMOND_SMP',
    'FIREBALL_FIGHT',
    'GAPPLE',
    'MACE',
    'MINECART',
    'NETHERITE_NODEBUFF',
    'NODEBUFF',
    'PARKOUR',
    'PEARL_FIGHT',
    'SOUP',
    'SPLEEF',
    'SUMO',
    'SWORD',
    'THE_BRIDGE',
    'VOID_FIGHT',
  ],
} as const satisfies Record<PikaNetworkGamemode, readonly string[]>;

export type PikaNetworkMode<G extends PikaNetworkGamemode> =
  (typeof PikaNetworkModes)[G][number];

export const PikaNetworkStats = {
  bedwars: {
    BED_DESTROYED: 'Beds destroyed',
    BOW_KILLS: 'Bow kills',
    FINAL_KILLS: 'Final kills',
    HIGHEST_WIN_STREAK: 'Highest winstreak reached',
    kills: 'Kills',
    played: 'Games played',
    wins: 'Wins',
  },
  dungeons: {
    BOSS_DAMAGE_DEALT_TOTAL: 'Total Boss Damage',
    BOSS_KILLS_TOTAL: 'Total Boss Kills',
    MOB_DAMAGE_DEALT_TOTAL: 'Total Mob Damage',
    MOB_KILLS_TOTAL: 'Total Mob Kills',
    PETS_DELETED: 'Pets Deleted',
    PETS_FUSED: 'Pets Fused',
    PETS_HATCHED: 'Pets Hatched',
    PETS_USED_IN_FUSION: 'Pets Used in Fusion',
    PITY_ROLLS: 'Pity Rolls',
    REBIRTH: 'Rebirth',
    TOTAL_BOMBS_THROWN: 'Total Bombs Thrown',
    TOTAL_CRYSTALS_OBTAINED: 'Total Crystals Obtained',
    TOTAL_ENCHANT_ACTIVATIONS: 'Total Enchant Activations',
    TOTAL_PERKS_ROLLED: 'Total Perks Rolled',
  },
  genpvp: {
    balance: 'Balance',
    CURRENT_KILLSTREAK: 'Current Killstreak',
    DEATHS: 'Deaths',
    HIGHEST_KILLSTREAK: 'Highest Killstreak',
    kills: 'Kills',
    LEVEL: 'Level',
  },
  kitpvp: {
    balance: 'Balance',
    CURRENT_KILLSTREAK: 'Current Killstreak',
    kills: 'Kills',
    KITPVP_LEVEL: 'Level',
    PRESTIGE: 'Prestige',
    TOTAL_KOTHS_WON: 'Total koths won',
  },
  oneblock: {
    balance: 'Balance',
    CUSTOM_CROPS_FARMED: 'Custom Crops Farmed',
    MOBS_KILLED: 'Mobs Killed',
    ONE_BLOCK_BROKEN: 'One Block Broken',
    PLAYER_LEVEL: 'Player Level',
  },
  opfactions: {
    balance: 'Balance',
    DEATHS: 'Deaths',
    HARVEST_SUGAR_CANE: 'Harvest Sugar Cane',
    HIGHEST_KILLSTREAK: 'Highest Killstreak',
    kills: 'Kills',
    MOBS_KILLED: 'Mobs Killed',
    PLAYER_LEVEL: 'Player Level',
    TOTAL_KOTHS_WON: 'Total koths won',
  },
  oplifesteal: {
    balance: 'Balance',
    BLOCKS_BROKEN: 'Blocks Broken',
    BLOCKS_PLACED: 'Blocks Placed',
    DEATHS: 'Deaths',
    HIGHEST_KILLSTREAK: 'Highest Killstreak',
    kills: 'Kills',
    MOBS_KILLED: 'Mobs Killed',
    PLAYER_LEVEL: 'Player Level',
  },
  opprison: {
    kills: null,
    PRISON_ASCENSION: 'Ascension',
    PRISON_BEACON_BALANCE: 'Beacons',
    PRISON_BLOCKS_BROKEN: 'Blocks Broken',
    PRISON_PRESTIGE: 'Prestige',
    PRISON_RAW_BLOCKS_BROKEN: 'Raw Blocks Broken',
    PRISON_TOKEN_BALANCE: 'Tokens',
  },
  opskyblock: {
    ADVENTURER_SKILL_LEVEL: 'Adventurer Skill Level',
    ALCHEMIST_SKILL_LEVEL: 'Alchemist Skill Level',
    ARCHERY_SKILL_LEVEL: 'Archery Skill Level',
    AXES_SKILL_LEVEL: 'Axes Skill Level',
    balance: 'Balance',
    BANKER_SKILL_LEVEL: 'Banker Skill Level',
    FARMER_SKILL_LEVEL: 'Farmer Skill Level',
    kills: null,
    LUCKY_SKILL_LEVEL: 'Lucky Skill Level',
    MINER_SKILL_LEVEL: 'Miner Skill Level',
    PLAYER_LEVEL: 'Player Level',
    SKILL_LEVEL: 'Skill Level',
    Souls: 'Souls',
    SPECIAL_ORES_MINED: 'Special Ores Mined',
    WIZARD_SKILL_LEVEL: 'Wizard Skill Level',
  },
  pillars: {
    kills: 'Kills',
    played: 'Games played',
    wins: 'Wins',
  },
  skymines: {
    balance: 'Balance',
    BLOCKS_MINED: 'Blocks Mined',
    BOSSES_KILLED: 'Bosses Killed',
    DEATHS: 'Deaths',
    HIGHEST_KILLSTREAK: 'Highest Killstreak',
    kills: 'Kills',
    PLAYER_LEVEL: 'Player Level',
  },
  skypvp: {
    balance: 'Balance',
    CURRENT_KILLSTREAK: 'Current Killstreak',
    DEATHS: 'Deaths',
    HIGHEST_KILLSTREAK: 'Highest Killstreak',
    kills: 'Kills',
    LUCKY_CRATES_OPENED: 'Lucky Crates Opened',
    RANK_RATING: 'Rank Rating',
  },
  survival: {
    balance: 'Balance',
    EXP_COLLECTED: 'EXP Collected',
    MOBS_KILLED: 'Mobs Killed',
    PLAYER_LEVEL: 'Player Level',
  },
  unrankedpractice: {
    HIGHEST_WIN_STREAK: 'Highest winstreak reached',
    kills: 'Kills',
    LOSSES: 'Losses',
    MELEE_DEALT: 'Hits dealt',
    MELEE_TAKEN: 'Hits taken',
    played: 'Games played',
    VOID_KILLS: 'Void kills',
    wins: 'Wins',
  },
} as const satisfies Record<PikaNetworkGamemode, Record<string, string | null>>;

export type PikaNetworkStat<G extends PikaNetworkGamemode> =
  keyof (typeof PikaNetworkStats)[G];

/**
 * querying the alias returns the same data as the canonical stat
 */
export const PikaNetworkStatAliases = {
  bedwars: {
    PROJECTILE_KILLS: 'BOW_KILLS',
  },
} as const;

export const PikaNetworkIntervals = ['total', 'weekly', 'monthly', 'yearly'] as const;
export type PikaNetworkInterval = (typeof PikaNetworkIntervals)[number];

/**
 * interval=yearly doesn't work outside these gamemodes.
 * enforced at the type and request level.
 */
export const YearlyCapableGamemodes = [
  'bedwars',
  'unrankedpractice',
] as const satisfies readonly PikaNetworkGamemode[];

export const PikaNetworkRequiredMode = {
  pillars: 'Seasonal',
} as const;

/**
 * ergonomic alias
 */
export const Gamemode = {
  BedWars: 'bedwars',
  Dungeons: 'dungeons',
  GenPvp: 'genpvp',
  KitPvp: 'kitpvp',
  OneBlock: 'oneblock',
  OpFactions: 'opfactions',
  OpLifesteal: 'oplifesteal',
  OpPrison: 'opprison',
  OpSkyBlock: 'opskyblock',
  Pillars: 'pillars',
  SkyMines: 'skymines',
  SkyPvp: 'skypvp',
  Survival: 'survival',
  UnrankedPractice: 'unrankedpractice',
} as const satisfies Record<string, PikaNetworkGamemode>;

export const Interval = {
  Total: 'total',
  Weekly: 'weekly',
  Monthly: 'monthly',
  Yearly: 'yearly',
} as const satisfies Record<string, PikaNetworkInterval>;

export const Mode = {
  BedWars: {
    AllModes: 'ALL_MODES',
    Doubles: 'DOUBLES',
    Quad: 'QUAD',
    Solo: 'SOLO',
    Triples: 'TRIPLES',
  },
  Dungeons: {
    AllModes: 'ALL_MODES',
  },
  GenPvp: {
    AllModes: 'ALL_MODES',
  },
  KitPvp: {
    AllModes: 'ALL_MODES',
  },
  OneBlock: {
    AllModes: 'ALL_MODES',
  },
  OpFactions: {
    AllModes: 'ALL_MODES',
  },
  OpLifesteal: {
    AllModes: 'ALL_MODES',
  },
  OpPrison: {
    AllModes: 'ALL_MODES',
  },
  OpSkyBlock: {
    AllModes: 'ALL_MODES',
  },
  Pillars: {
    Seasonal: 'Seasonal',
  },
  SkyMines: {
    AllModes: 'ALL_MODES',
  },
  SkyPvp: {
    AllModes: 'ALL_MODES',
  },
  Survival: {
    AllModes: 'ALL_MODES',
  },
  UnrankedPractice: {
    AllModes: 'ALL_MODES',
    Archer: 'ARCHER',
    AxePvp: 'AXE_PVP',
    AxeShield: 'AXE_SHIELD',
    BattleRush: 'BATTLE_RUSH',
    BedFight: 'BED_FIGHT',
    Boxing: 'BOXING',
    BuildUhc: 'BUILD_UHC',
    Combo: 'COMBO',
    Crystal: 'CRYSTAL',
    Debuff: 'DEBUFF',
    DiamondSmp: 'DIAMOND_SMP',
    FireballFight: 'FIREBALL_FIGHT',
    Gapple: 'GAPPLE',
    Mace: 'MACE',
    Minecart: 'MINECART',
    NetheriteNodebuff: 'NETHERITE_NODEBUFF',
    Nodebuff: 'NODEBUFF',
    Parkour: 'PARKOUR',
    PearlFight: 'PEARL_FIGHT',
    Soup: 'SOUP',
    Spleef: 'SPLEEF',
    Sumo: 'SUMO',
    Sword: 'SWORD',
    TheBridge: 'THE_BRIDGE',
    VoidFight: 'VOID_FIGHT',
  },
} as const;

export const Stat = {
  BedWars: {
    BedDestroyed: 'BED_DESTROYED',
    BowKills: 'BOW_KILLS',
    FinalKills: 'FINAL_KILLS',
    HighestWinStreak: 'HIGHEST_WIN_STREAK',
    Kills: 'kills',
    Played: 'played',
    Wins: 'wins',
  },
  Dungeons: {
    BossDamageDealtTotal: 'BOSS_DAMAGE_DEALT_TOTAL',
    BossKillsTotal: 'BOSS_KILLS_TOTAL',
    MobDamageDealtTotal: 'MOB_DAMAGE_DEALT_TOTAL',
    MobKillsTotal: 'MOB_KILLS_TOTAL',
    PetsDeleted: 'PETS_DELETED',
    PetsFused: 'PETS_FUSED',
    PetsHatched: 'PETS_HATCHED',
    PetsUsedInFusion: 'PETS_USED_IN_FUSION',
    PityRolls: 'PITY_ROLLS',
    Rebirth: 'REBIRTH',
    TotalBombsThrown: 'TOTAL_BOMBS_THROWN',
    TotalCrystalsObtained: 'TOTAL_CRYSTALS_OBTAINED',
    TotalEnchantActivations: 'TOTAL_ENCHANT_ACTIVATIONS',
    TotalPerksRolled: 'TOTAL_PERKS_ROLLED',
  },
  GenPvp: {
    CurrentKillstreak: 'CURRENT_KILLSTREAK',
    Deaths: 'DEATHS',
    HighestKillstreak: 'HIGHEST_KILLSTREAK',
    Level: 'LEVEL',
    Balance: 'balance',
    Kills: 'kills',
  },
  KitPvp: {
    CurrentKillstreak: 'CURRENT_KILLSTREAK',
    KitpvpLevel: 'KITPVP_LEVEL',
    Prestige: 'PRESTIGE',
    TotalKothsWon: 'TOTAL_KOTHS_WON',
    Balance: 'balance',
    Kills: 'kills',
  },
  OneBlock: {
    CustomCropsFarmed: 'CUSTOM_CROPS_FARMED',
    MobsKilled: 'MOBS_KILLED',
    OneBlockBroken: 'ONE_BLOCK_BROKEN',
    PlayerLevel: 'PLAYER_LEVEL',
    Balance: 'balance',
  },
  OpFactions: {
    Deaths: 'DEATHS',
    HarvestSugarCane: 'HARVEST_SUGAR_CANE',
    HighestKillstreak: 'HIGHEST_KILLSTREAK',
    MobsKilled: 'MOBS_KILLED',
    PlayerLevel: 'PLAYER_LEVEL',
    TotalKothsWon: 'TOTAL_KOTHS_WON',
    Balance: 'balance',
    Kills: 'kills',
  },
  OpLifesteal: {
    BlocksBroken: 'BLOCKS_BROKEN',
    BlocksPlaced: 'BLOCKS_PLACED',
    Deaths: 'DEATHS',
    HighestKillstreak: 'HIGHEST_KILLSTREAK',
    MobsKilled: 'MOBS_KILLED',
    PlayerLevel: 'PLAYER_LEVEL',
    Balance: 'balance',
    Kills: 'kills',
  },
  OpPrison: {
    PrisonAscension: 'PRISON_ASCENSION',
    PrisonBeaconBalance: 'PRISON_BEACON_BALANCE',
    PrisonBlocksBroken: 'PRISON_BLOCKS_BROKEN',
    PrisonPrestige: 'PRISON_PRESTIGE',
    PrisonRawBlocksBroken: 'PRISON_RAW_BLOCKS_BROKEN',
    PrisonTokenBalance: 'PRISON_TOKEN_BALANCE',
    Kills: 'kills',
  },
  OpSkyBlock: {
    AdventurerSkillLevel: 'ADVENTURER_SKILL_LEVEL',
    AlchemistSkillLevel: 'ALCHEMIST_SKILL_LEVEL',
    ArcherySkillLevel: 'ARCHERY_SKILL_LEVEL',
    AxesSkillLevel: 'AXES_SKILL_LEVEL',
    BankerSkillLevel: 'BANKER_SKILL_LEVEL',
    FarmerSkillLevel: 'FARMER_SKILL_LEVEL',
    LuckySkillLevel: 'LUCKY_SKILL_LEVEL',
    MinerSkillLevel: 'MINER_SKILL_LEVEL',
    PlayerLevel: 'PLAYER_LEVEL',
    SkillLevel: 'SKILL_LEVEL',
    SpecialOresMined: 'SPECIAL_ORES_MINED',
    Souls: 'Souls',
    WizardSkillLevel: 'WIZARD_SKILL_LEVEL',
    Balance: 'balance',
    Kills: 'kills',
  },
  Pillars: {
    Kills: 'kills',
    Played: 'played',
    Wins: 'wins',
  },
  SkyMines: {
    BlocksMined: 'BLOCKS_MINED',
    BossesKilled: 'BOSSES_KILLED',
    Deaths: 'DEATHS',
    HighestKillstreak: 'HIGHEST_KILLSTREAK',
    PlayerLevel: 'PLAYER_LEVEL',
    Balance: 'balance',
    Kills: 'kills',
  },
  SkyPvp: {
    CurrentKillstreak: 'CURRENT_KILLSTREAK',
    Deaths: 'DEATHS',
    HighestKillstreak: 'HIGHEST_KILLSTREAK',
    LuckyCratesOpened: 'LUCKY_CRATES_OPENED',
    RankRating: 'RANK_RATING',
    Balance: 'balance',
    Kills: 'kills',
  },
  Survival: {
    ExpCollected: 'EXP_COLLECTED',
    MobsKilled: 'MOBS_KILLED',
    PlayerLevel: 'PLAYER_LEVEL',
    Balance: 'balance',
  },
  UnrankedPractice: {
    HighestWinStreak: 'HIGHEST_WIN_STREAK',
    Losses: 'LOSSES',
    MeleeDealt: 'MELEE_DEALT',
    MeleeTaken: 'MELEE_TAKEN',
    VoidKills: 'VOID_KILLS',
    Kills: 'kills',
    Played: 'played',
    Wins: 'wins',
  },
} as const;

export const StatKey = {
  BedWars: {
    BedDestroyed: 'Beds destroyed',
    BowKills: 'Bow kills',
    FinalKills: 'Final kills',
    HighestWinStreak: 'Highest winstreak reached',
    Kills: 'Kills',
    Played: 'Games played',
    Wins: 'Wins',
  },
  Dungeons: {
    BossDamageDealtTotal: 'Total Boss Damage',
    BossKillsTotal: 'Total Boss Kills',
    MobDamageDealtTotal: 'Total Mob Damage',
    MobKillsTotal: 'Total Mob Kills',
    PetsDeleted: 'Pets Deleted',
    PetsFused: 'Pets Fused',
    PetsHatched: 'Pets Hatched',
    PetsUsedInFusion: 'Pets Used in Fusion',
    PityRolls: 'Pity Rolls',
    Rebirth: 'Rebirth',
    TotalBombsThrown: 'Total Bombs Thrown',
    TotalCrystalsObtained: 'Total Crystals Obtained',
    TotalEnchantActivations: 'Total Enchant Activations',
    TotalPerksRolled: 'Total Perks Rolled',
  },
  GenPvp: {
    Balance: 'Balance',
    CurrentKillstreak: 'Current Killstreak',
    Deaths: 'Deaths',
    HighestKillstreak: 'Highest Killstreak',
    Kills: 'Kills',
    Level: 'Level',
  },
  KitPvp: {
    Balance: 'Balance',
    CurrentKillstreak: 'Current Killstreak',
    Kills: 'Kills',
    KitpvpLevel: 'Level',
    Prestige: 'Prestige',
    TotalKothsWon: 'Total koths won',
  },
  OneBlock: {
    Balance: 'Balance',
    CustomCropsFarmed: 'Custom Crops Farmed',
    MobsKilled: 'Mobs Killed',
    OneBlockBroken: 'One Block Broken',
    PlayerLevel: 'Player Level',
  },
  OpFactions: {
    Balance: 'Balance',
    Deaths: 'Deaths',
    HarvestSugarCane: 'Harvest Sugar Cane',
    HighestKillstreak: 'Highest Killstreak',
    Kills: 'Kills',
    MobsKilled: 'Mobs Killed',
    PlayerLevel: 'Player Level',
    TotalKothsWon: 'Total koths won',
  },
  OpLifesteal: {
    Balance: 'Balance',
    BlocksBroken: 'Blocks Broken',
    BlocksPlaced: 'Blocks Placed',
    Deaths: 'Deaths',
    HighestKillstreak: 'Highest Killstreak',
    Kills: 'Kills',
    MobsKilled: 'Mobs Killed',
    PlayerLevel: 'Player Level',
  },
  OpPrison: {
    PrisonAscension: 'Ascension',
    PrisonBeaconBalance: 'Beacons',
    PrisonBlocksBroken: 'Blocks Broken',
    PrisonPrestige: 'Prestige',
    PrisonRawBlocksBroken: 'Raw Blocks Broken',
    PrisonTokenBalance: 'Tokens',
  },
  OpSkyBlock: {
    AdventurerSkillLevel: 'Adventurer Skill Level',
    AlchemistSkillLevel: 'Alchemist Skill Level',
    ArcherySkillLevel: 'Archery Skill Level',
    AxesSkillLevel: 'Axes Skill Level',
    Balance: 'Balance',
    BankerSkillLevel: 'Banker Skill Level',
    FarmerSkillLevel: 'Farmer Skill Level',
    LuckySkillLevel: 'Lucky Skill Level',
    MinerSkillLevel: 'Miner Skill Level',
    PlayerLevel: 'Player Level',
    SkillLevel: 'Skill Level',
    Souls: 'Souls',
    SpecialOresMined: 'Special Ores Mined',
    WizardSkillLevel: 'Wizard Skill Level',
  },
  Pillars: {
    Kills: 'Kills',
    Played: 'Games played',
    Wins: 'Wins',
  },
  SkyMines: {
    Balance: 'Balance',
    BlocksMined: 'Blocks Mined',
    BossesKilled: 'Bosses Killed',
    Deaths: 'Deaths',
    HighestKillstreak: 'Highest Killstreak',
    Kills: 'Kills',
    PlayerLevel: 'Player Level',
  },
  SkyPvp: {
    Balance: 'Balance',
    CurrentKillstreak: 'Current Killstreak',
    Deaths: 'Deaths',
    HighestKillstreak: 'Highest Killstreak',
    Kills: 'Kills',
    LuckyCratesOpened: 'Lucky Crates Opened',
    RankRating: 'Rank Rating',
  },
  Survival: {
    Balance: 'Balance',
    ExpCollected: 'EXP Collected',
    MobsKilled: 'Mobs Killed',
    PlayerLevel: 'Player Level',
  },
  UnrankedPractice: {
    HighestWinStreak: 'Highest winstreak reached',
    Kills: 'Kills',
    Losses: 'Losses',
    MeleeDealt: 'Hits dealt',
    MeleeTaken: 'Hits taken',
    Played: 'Games played',
    VoidKills: 'Void kills',
    Wins: 'Wins',
  },
} as const;

export type PikaNetworkStatKey<G extends PikaNetworkGamemode> = Exclude<
  (typeof PikaNetworkStats)[G][keyof (typeof PikaNetworkStats)[G]],
  null
>;
